### ISSUE TITLE
Is it possible to get access to intermediate node in nngraph?

### ISSUE THREAD

**Issue by blackyang** [torch/nngraph#102]
Sorry I didn't find related documentations. I would also apologize if github issues is not a good place to ask such questions (e.g if there is a google group for such discussions)

What I'd like to do is something similar to:
```
m = nn.Sequential()
m:add(nn.Linear(5,5))
m:get(1)
```

I have a rnn.GRU module in my gModule, and I have to manually call `forget()` function and change `self.userPrevOutput` sometimes. So it would be great if I can get access to intermediate node. Otherwise, I have to move rnn.GRU out of gModule :(

Thanks in advance!

**Comment by blackyang** [comment]
Oh after taking a look at gmodule.lua code, I thinks I can do this:

```
m = nn.gModule()
m.forwardnodes[i].data.module
```

correct me if there is any problem :)

**Comment by soumith** [comment]
you can also take a look at https://github.com/bshillingford/nnquery for getting nodes from very large nngraph networks.

**Comment by blackyang** [comment]
Thanks for the pointer!

**Comment by blackyang** [comment]
Just saw this again, a better way I have found is to:
1. add annotations by calling `:annotate{name = 'name'}` function
2. find the annotated module, e.g.
```
for k, v in ipairs(model.forwardnodes) do
    if v.data.annotations.name == 'name' then
        module = v.data.module
    end
end
```

**Comment by suhmily** [comment]
May I ask if I can get access to the output of intermediate layers?

**Comment by blackyang** [comment]
@suhmily yes, simply `module.outputs`

**Comment by blackyang** [comment]
btw, can also use
```
model.findModules('nn.Linear')[i]
```
to get the i-th nn.Linear module
