### ISSUE TITLE
will the model run faster when I use nngraph?

### ISSUE THREAD

**Issue by anoidgit** [torch/nngraph#120]
For example, I could get a 2-layer MLP with Container or nngraph, will it be a little bit faster when I use nngraph?

**Comment by nhynes** [comment]
No. Just look at the difference in complexities of the respective `updateOutput`s. `nn.Sequential` is a simple loop whereas `nngraph` has several loops, allocations, and conditionals.

**Comment by anoidgit** [comment]
@nhynes thank you, I think it was something like theano before.
