### ISSUE TITLE
Removing Nodes 

### ISSUE THREAD

**Issue by amdegroot** [torch/nngraph#125]
Is there an easy way to remove the last node or two from an architecture? I feel like this would be a fairly common operation, especially when adding a different classifier to fine-tune a model.

**Comment by soumith** [comment]
@amdegroot unfortunately (after digging into the code), there seems to be no straight-forward way of doing this. You can put your last few nodes, i.e. the classifier into an nn.Sequential and after training, remove the nodes inside the sequential by using the :apply() call on the nngraph, getting to the sequential module, and removing nodes from the sequential module's .modules table.

**Comment by amdegroot** [comment]
Ah, ok that's actually a great idea, I will try that out.  Unfortunate that there is not a better way to remove nodes.  I wonder if it would be difficult to add some of that functionality to the nnQuery package..  Thanks for getting back to me!
