### ISSUE TITLE
minus '-' syntax not working

### ISSUE THREAD

**Issue by dno89** [torch/nngraph#128]
Trying to execute the example with the '-' syntax presented in  [https://github.com/torch/nngraph#more-fun-with-graphs](url) results in:
`nn.Identity has no negation operator`

Replacing `input = - nn.Identity()` with  `input = nn.Identity()()` then leads to:
`both nngraph.Node and nn.Linear have no substraction operator`

**Comment by soumith** [comment]
did you update your nngraph package?
luarocks install nngraph

**Comment by dno89** [comment]
Apparently I had an older version.
Thank you very much.
