### ISSUE TITLE
Plot 'net' of 'cvpr2015/Deep Learning with Torch.ipynb' with nngraph

### ISSUE THREAD

**Issue by lnastansky** [torch/nngraph#129]
What is the easiest way / LuaScript to add a nngraph plotting demo of the 'net' in the excellent 'Torch.ipynb' Demo Tutorial?

Thanks for help,
Ludwig

**Comment by soumith** [comment]
since that particular network is not an nngraph based network, the easiest way is to use plotting from this package: https://github.com/fmassa/optimize-net#visualizing-the-memory-reuse

**Comment by lnastansky** [comment]
Thanks - works fine now.
