### ISSUE TITLE
ittermediate feature maps

### ISSUE THREAD

**Issue by varghesealex90** [torch/nngraph#149]
Hi;
I made a very simple convolution network using nngraph. I would like to see the intermediate convolution features
require 'nngraphs'

a=nn.Identity() ()
b=nn.SpatialConvolution(3,32,5,5)(a)
c= nn.SpatialConvolution(32,4,5,5)(b)

model= nn.Sequential()
model:add(nn.gModule({a},{c}))

Now I would like to see the feature map from the first conv. 

Please help

**Comment by Naruto-Sasuke** [comment]
#146
