### ISSUE TITLE
Qtsvg problem

### ISSUE THREAD

**Issue by ssakhavi** [torch/nngraph#35]
Hi

I can't manage to get this package to work. the error comes up when ``require 'qtsvg'`` is being used. 
the error is as follows:

require 'qtsvg'
/usr/local/share/lua/5.1/qtsvg/init.lua:2: module 'qt' not found:No LuaRocks module found for qt
	no field package.preload['qt']
	no file '/usr/local/share/lua/5.1/qt.lua'
	no file '/usr/local/share/lua/5.1/qt/init.lua'
	no file '/home/siavash/.luarocks/share/lua/5.1/qt.lua'
	no file '/home/siavash/.luarocks/share/lua/5.1/qt/init.lua'
	no file '/usr/local/share/lua/5.1/qt.lua'
	no file '/usr/local/share/lua/5.1/qt/init.lua'
	no file '/home/siavash/.luarocks/share/lua/5.1/qt.lua'
	no file '/home/siavash/.luarocks/share/lua/5.1/qt/init.lua'
	no file '/usr/local/share/lua/5.1/qt.lua'
	no file '/usr/local/share/lua/5.1/qt/init.lua'
	no file './qt.lua'
	no file '/usr/local/share/luajit-2.0.2/qt.lua'
	no file '/usr/local/share/lua/5.1/qt.lua'
	no file '/usr/local/share/lua/5.1/qt/init.lua'
	no file '/usr/local/lib/lua/5.1/qt.so'
	no file '/home/siavash/.luarocks/lib/lua/5.1/qt.so'
	no file '/usr/local/lib/lua/5.1/qt.so'
	no file '/home/siavash/.luarocks/lib/lua/5.1/qt.so'
	no file './qt.so'
	no file '/usr/local/lib/lua/5.1/qt.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/qtsvg/init.lua:2: in main chunk
	[C]: in function 'f'
	[string "local f = function() return require 'qtsvg' e..."]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/trepl/init.lua:553: in function </usr/local/share/lua/5.1/trepl/init.lua:489>	

what can be the problem?

**Comment by AjayTalati** [comment]
You can specify a filename to save the .svg to the disk instead,

`graph.dot(mlp.fg, 'MLP', 'outputBasename')`

That works great! Thanks :+1:  :+1:

**Comment by donglixp** [comment]
@fidlej Thanks! This also works for me.
