### ISSUE TITLE
Speed reduction?

### ISSUE THREAD

**Issue by alexbw** [torch/nngraph#38]
Couldn't find a mailing list for nngraph so I'll ask here. Is there any speed hit when using nngraph to specify a model over vanilla nn? Also, do these models port to the GPU like NN models do?

**Comment by soumith** [comment]
yes, nngraph has a small overhead to use. @koraykv is heading an effort to clean nngraph and possibly remove some of the overhead.

**Comment by alexbw** [comment]
Closing, question answered.

**Comment by alexbw** [comment]
Curious what the status of the cleaning?

**Comment by soumith** [comment]
Its just master afaik.

**Comment by alexbw** [comment]
Should close?

**Comment by koraykv** [comment]
There is no explicit cleaning happening. If there are specific things people want we can work on that. I have added a benchmark file to the main repo which measures the overhead using a network that splits and merges several hundred times. In my experiments I have seen 10-15% overhead when using very small number of hidden units (<32). For anything reasonable (>128 hidden units) the effects seems to be negligible.

Having said that, I am interested to hear what others find and having benchmarks would make it easier to find bottlenecks.

**Comment by hughperkins** [comment]
would be good to have some objective measures, in a concise table, like

```
nngraph timings using model XXXX on ubuntu 14.04 using a YYY processor
Number hidden units      Time using nn blocks    Time using nngraph    Percentage overhead
1
10
100
1000
```

**Comment by soumith** [comment]
I think https://github.com/torch/nngraph/blob/master/test/speed.lua achieves that.
