### ISSUE TITLE
Display gradOutput 

### ISSUE THREAD

**Issue by AjayTalati** [torch/nngraph#43]
How do you get graphviz to display `gradOutput`? 

It does'nt display automatically on my backward graphs?  

![system_backward_graph](https://cloud.githubusercontent.com/assets/10279780/6673202/4152c27a-cc09-11e4-853e-b53c7ac2441f.jpg)

I've done something really stupid, and I can't backprop ??? :-1:

**Comment by fidlej** [comment]
I guess, you haven't run the net forward and backward yet.

**Comment by AjayTalati** [comment]
Thanks !!!

**Comment by AjayTalati** [comment]
I did'nt take the gradients of my sampler module which has inputs, `mu_t` and `sigma_t`, and outputs

`Z_t= mu_t + sigma_t * N(0,1)`

I was careless, and put `self.gradInput = gradOutput` in my sampler module, instead of

`self.gradInput = {}`
`self.gradInput[1] = 1`
`self.gradInput[2] = torch.randn( input[2]:size() )`

So when graphviz tried to make the graph, it gave a `split table` error, which is good, because it spotted my mistake :+1: :)

![test_module_backward_graph](https://cloud.githubusercontent.com/assets/10279780/6676872/1b77c2c0-cc23-11e4-8365-3123ec0a22fb.jpg)
