### ISSUE TITLE
Seems not to be installable via luarocks?

### ISSUE THREAD

**Issue by hughperkins** [torch/nngraph#51]
- seems not to be installable via luarocks?  I tried various variations of `luarocks install nngraph`, but none seemed to work for me?  Searching at https://luarocks.org/search?q=nngraph seems not to provide any results?

**Comment by hughperkins** [comment]
Where to find 'graph'?  I am trying to install nngraph by git cloneing this repository, nad 'luarocks install nngraph-scm-1.rockspec', but it hsa a dependency on 'graph', and I'm not sure how/where to find that?  (seems not to be in luarocks.org either? https://luarocks.org/search?q=graph )

**Comment by hughperkins** [comment]
Where to find 'graph'?  I am trying to install nngraph by git cloneing this repository, nad 'luarocks install nngraph-scm-1.rockspec', but it hsa a dependency on 'graph', and I'm not sure how/where to find that?  (seems not to be in luarocks.org either? https://luarocks.org/search?q=graph )

**Comment by hughperkins** [comment]
Ok, found how to install it by following the breadcrumbs to https://github.com/oxford-cs-ml-2015/practical1/blob/master/install-torch.sh , which gave me:
```
    cd /tmp/torch-install-scripts-$USER
    git clone git://github.com/koraykv/torch-graph.git
    cd torch-graph
    luarocks make
    cd ..
    git clone git://github.com/koraykv/torch-nngraph.git
    cd torch-nngraph
    luarocks make

```

**Comment by oukohou** [comment]
seems  issue #52 got another way succeed:
`luarocks --from=https://raw.githubusercontent.com/torch/rocks/master/ install nngraph`
hope helpful.
