### ISSUE TITLE
failing local install

### ISSUE THREAD

**Issue by kelvinxu** [torch/nngraph#55]
Hi,

I am trying to install nngraph locally using `$ luarocks install --local nngraph`. I was surprised to see that it said that I had missing dependencies for nngraph, even though I could seemly import them with require.
```
Missing dependencies for nngraph:
torch >= 7.0
nn
graph
```
After trying to build I end up with the following message.
```
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/share/torch7-dist/install/share/cmake/torch/TorchExports.cmake
CMake Error at cmake_install.cmake:48 (FILE):
 file INSTALL cannot copy file
 "/tmp/luarocks_torch-scm-1-446/torch7/build/CMakeFiles/Export/share/cmake/torch/TorchExports.cmake"
 to "/usr/share/torch7-dist/install/share/cmake/torch/TorchExports.cmake".
make: *** [install] Error 1

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/torch-scm-1.rockspec - Build error: Failed installing.
```
Would appreciate any help.

**Comment by hughperkins** [comment]
Is torch installed in ~/torch?  Can you try running the following first?:
```
export PATH=/home/user/torch/install/bin:$PATH
export LD_LIBRARY_PATH=/home/user/torch/install/lib:$LD_LIBRARY_PATH 
export DYLD_LIBRARY_PATH=/home/user/torch/install/lib:$DYLD_LIBRARY_PATH 

eval $(luarocks path --bin)
```

**Comment by kelvinxu** [comment]
Hey Hugh,
I tried what you suggested and had no luck. It is installed in /usr/share/torch7-dist.

**Comment by hughperkins** [comment]
Normally it would be installed in ~/torch.  I think you might consider reinstalling from scratch, following Soumith's instructions at https://github.com/torch/distro

**Comment by kelvinxu** [comment]
Alright thanks
