### ISSUE TITLE
attempt to call field 'gvContext' (a nil value)

### ISSUE THREAD

**Issue by hughperkins** [torch/nngraph#59]
On ubuntu 14.04, to get nngraph graphviz t owork, I need to changes lines 29 and 30 of graphviz.lua to:

```
local graphvizOk, graphviz = pcall(function() return ffi.load('libgvc.so.6') end)
local cgraphOk, cgraph = pcall(function() return ffi.load('libcgraph.so.6') end)
```

(ie adding postfix '.6' to each of hte filenames)

(I'm not sure how to do this portably though, hence putting this as an issue, rather than a PR.

**Comment by soumith** [comment]
hmmm, that kinda sucks. There seems to be no portable way except chaining the pcalls one after another....

**Comment by koraykv** [comment]
we can always make a list of lib names and try them, but I thought ffi.load
had some sort of search depending on the architecture it is running on.

**Comment by koraykv** [comment]
I also thought would have a symlink from libgvc.so or libgvc.so.6

**Comment by hughperkins** [comment]
@soumith, yes, chaining the pcalls one after the other seems to be a plausible approach

@koraykv on my ubuntu 14.04 64-bit system:
```
$ dpkg -L libgvc6 | grep gvc.so
/usr/lib/libgvc.so.6.0.0
/usr/lib/libgvc.so.6
$ ls /usr/lib/libgvc*
/usr/lib/libgvc.so.6  /usr/lib/libgvc.so.6.0.0
```

**Comment by soumith** [comment]
I think we'll just have to maintain a list of library names to try then (sucks but no other way)

**Comment by donglixp** [comment]
@hughperkins Thanks! Your solution also works for me.
