### ISSUE TITLE
id should be on the data, so invariant

### ISSUE THREAD

**Issue by hughperkins** [torch/nngraph#71]
node ids should be on the `data` rather than on the `node`, so that they are invariant.

eg, currently node ids in fg and node ids in bg are different, I think?

**Comment by koraykv** [comment]
See https://github.com/torch/nngraph/blob/99919fa260dd2ca33347c06da04dce5931f9fcc8/gmodule.lua#L108

The node id s are coming from underlying graph class in torch/graph so they need to be on the node. As you said, the forward and backward graphs are separate graphs so nodes have different ids, but of course the data is shared between separate graphs.

**Comment by hughperkins** [comment]
graph is aware of data object, and could inject an id into it.  It would obviously have to be careful not to overwrite some existing property also called 'data.id'.

**Comment by koraykv** [comment]
I agree with you, we might want to inject id into id. Just for information, gModule constructor does this by injecting a filed named forwardNodeId into data. If you are trying something, you can rely on that now.

**Comment by hughperkins** [comment]
Ah, good point about forwardNodeId
=> closing
