### ISSUE TITLE
nodes should have parent link

### ISSUE THREAD

**Issue by hughperkins** [torch/nngraph#72]
nodes should have parent link.  would make certain transformations much easier (or rather: possible. the easiest way to achieve them is precisely to add the parents, or to create an associative map of nodes to parents).

**Comment by koraykv** [comment]
I think this should be done in torch/graph. I tried to keep the initial structure to a minimum as much as possible to avoid future problems and minimize bookkeeping. Not having a parent object was one of these decisions, I did not need them for the algorithms implemented. If there is a need, it can be added.

**Comment by hughperkins** [comment]
> I think this should be done in torch/graph.

Ok

**Comment by hughperkins** [comment]
I might just put this in a separate graph-like structure, and have a way of converting between nngraph <-> other-graphlike-structure.
=> closed
