### ISSUE TITLE
should be a method to reduce an edge in a graph

### ISSUE THREAD

**Issue by hughperkins** [torch/nngraph#73]
There should be a method to reduce an edge in a graph, such that it continues to render correctly, and the graph data remains self-consistent.

**Comment by koraykv** [comment]
Sure, maybe this method should be in torch/graph? There is an attempt in simple_print.lua that aims to produce smaller graphs just for display.

**Comment by hughperkins** [comment]
> Sure, maybe this method should be in torch/graph?

Ok

**Comment by hughperkins** [comment]
I might just put this in a separate graph-like structure, and have a way of converting between nngraph <-> other-graphlike-structure.
=> closed
